name: akhdefov2
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h63175ca_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h8d17308_3
  - arosics=1.9.0=py310h5588dad_1
  - arrow-cpp=12.0.0=h57928b3_1_cpu
  - asciitree=0.3.3=py_2
  - asf_search=6.5.0=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.6.27=h0e8f9f7_0
  - aws-c-cal=0.5.26=h3200b0f_0
  - aws-c-common=0.8.17=hcfcfb64_0
  - aws-c-compression=0.2.16=h50f2975_6
  - aws-c-event-stream=0.2.20=h03f8742_6
  - aws-c-http=0.7.7=h1ea9cf2_3
  - aws-c-io=0.13.21=h09d0bb2_4
  - aws-c-mqtt=0.8.11=h9028ce9_0
  - aws-c-s3=0.3.0=h8e18d2d_1
  - aws-c-sdkutils=0.1.9=h50f2975_1
  - aws-checksums=0.1.14=h50f2975_6
  - aws-crt-cpp=0.20.1=h2d50ba6_2
  - aws-sdk-cpp=1.10.57=h0fa2e13_11
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=hdccc3a2_0
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.78.0=h9f4b32c_3
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py310h8d17308_1005
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.18.1=h8ffe710_0
  - c-blosc2=2.8.0=h183a6f4_1
  - ca-certificates=2023.11.17=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cairo=1.16.0=hd694305_1014
  - cartopy=0.21.1=py310hdfb2c83_1
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.15.1=py310h628cb3f_3
  - cfitsio=4.2.0=h9ebe7e4_0
  - cftime=1.6.2=py310h9b08ddd_1
  - charls=2.4.1=h1537add_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - chart-studio=1.1.0=pyh9f0ad1d_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - cmocean=3.0.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contextily=1.3.0=pyhd8ed1ab_0
  - contourpy=1.0.7=py310h232114e_0
  - cryptography=40.0.2=py310h6e82f81_0
  - curl=8.0.1=h68f0423_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.34=py310h00ffb61_0
  - cytoolz=0.12.0=py310h8d17308_1
  - dateparser=1.1.8=pyhd8ed1ab_0
  - dav1d=1.0.0=h8ffe710_1
  - debugpy=1.6.7=py310h00ffb61_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - earthpy=0.9.4=pyhd8ed1ab_0
  - emcee=3.1.4=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=h63175ca_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_h38027f0_107
  - fiona=1.9.3=py310h4a685fe_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.4=py310h8d17308_0
  - freetype=2.12.1=h546665d_1
  - freexl=1.0.6=h67ca5e6_1
  - fsspec=2023.5.0=pyh1a96a4e_0
  - gdal=3.6.3=py310h644bc08_1
  - geoarray=0.16.1=py310h5588dad_0
  - geocube=0.4.2=pyhd8ed1ab_1
  - geographiclib=1.52=pyhd8ed1ab_0
  - geojson=3.0.1=pyhd8ed1ab_0
  - geopandas=0.13.0=pyhd8ed1ab_0
  - geopandas-base=0.13.0=pyha770c72_0
  - geoplot=0.5.1=pyhd8ed1ab_0
  - geopy=2.3.0=pyhd8ed1ab_0
  - geos=3.11.2=h1537add_0
  - geotiff=1.7.1=hb4c6682_7
  - geowombat=2.1.6=py310h4d64026_1
  - gettext=0.21.1=h5728263_0
  - gflags=2.2.2=ha925a31_1004
  - giflib=5.2.1=h64bf75a_3
  - glib=2.76.2=h12be248_0
  - glib-tools=2.76.2=h12be248_0
  - glog=0.6.0=h4797de2_0
  - graphviz=2.38.0=h6538335_1011
  - gst-plugins-base=1.22.0=h001b923_2
  - gstools=1.4.1=py310h1c4a608_0
  - gstreamer=1.22.0=h6b5321d_2
  - h5netcdf=1.1.0=pyhd8ed1ab_1
  - h5py=3.8.0=nompi_py310hae7a582_100
  - hankel=1.2.1=pyhd8ed1ab_0
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.12.2=nompi_h57737ce_101
  - holoviews=1.16.0=pyhd8ed1ab_0
  - hyp3_sdk=4.0.0=pyhd8ed1ab_0
  - icu=70.1=h0e60522_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py310h63bd355_1
  - imageio=2.28.1=pyh24c5eb1_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipykernel=6.23.1=pyh025b116_0
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipython=8.13.2=pyh08f2357_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h5588dad_8
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310h5588dad_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jxrlib=1.1=h8ffe710_2
  - kealib=1.5.0=h61be68b_0
  - kiwisolver=1.4.4=py310h232114e_1
  - krb5=1.20.1=heb0366b_0
  - lazy_loader=0.2=pyhd8ed1ab_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230125.0=cxx17_h63175ca_1
  - libaec=1.0.6=h63175ca_1
  - libarrow=12.0.0=h91bed3e_1_cpu
  - libavif=0.11.1=h8f5c5bc_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libclang13=15.0.7=default_h77d9078_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.0.1=h68f0423_0
  - libdeflate=1.17=hcfcfb64_0
  - libevent=2.1.12=hf43717d_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.6.3=hd256549_1
  - libglib=2.76.2=he8f3873_0
  - libgoogle-cloud=2.10.0=h00b2bdc_0
  - libgrpc=1.54.2=h32da247_0
  - libhwloc=2.9.1=h51c2c0f_0
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - libkml=1.3.0=hf2ab4e4_1015
  - liblapack=3.9.0=16_win64_mkl
  - libnetcdf=4.9.1=nompi_h83fa41b_102
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libpq=15.3=ha9684e8_0
  - libprotobuf=3.21.12=h12be248_0
  - librttopo=1.1.0=he1da8c1_13
  - libsodium=1.0.18=h8d14728_1
  - libspatialindex=1.9.3=h39d44d4_4
  - libspatialite=5.0.1=h2bb424f_24
  - libsqlite=3.41.2=hcfcfb64_1
  - libssh2=1.10.0=h9a1e1f7_3
  - libthrift=0.18.1=h9ce19ad_1
  - libtiff=4.5.0=hc3b8658_5
  - libutf8proc=2.8.0=h82a8f57_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.4=hc3477c8_0
  - libzip=1.9.2=h519de47_1
  - libzlib=1.2.13=hcfcfb64_4
  - libzopfli=1.0.3=h0e60522_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py310hbbb2075_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markdown=3.4.3=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py310h8d17308_0
  - matplotlib-base=3.7.1=py310h51140c5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - matplotlib-scalebar=0.8.1=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - meshio=5.3.4=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.7.4=pyhd8ed1ab_0
  - nbconvert=7.4.0=pyhd8ed1ab_0
  - nbconvert-core=7.4.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.3=nompi_py310hf10f414_100
  - networkx=3.1=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numcodecs=0.11.0=py310h00ffb61_1
  - odc-geo=0.3.3=pyhd8ed1ab_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.2.0=hcfcfb64_0
  - orc=1.8.3=hada7b9e_0
  - packaging=23.1=pyhd8ed1ab_0
  - palettable=3.3.3=pyhd8ed1ab_0
  - pandoc=2.19.2=h57928b3_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.14.4=pyhd8ed1ab_0
  - param=1.13.0=pyh1a96a4e_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py310h3dcae36_0
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.1=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=h934c637_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.3=hd87cd2b_0
  - proj=9.1.1=heca977f_2
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-tools-ds=0.21.1=py310h5588dad_0
  - pyamg=5.0.0=py310hf19232d_0
  - pyarrow=12.0.0=py310hd1a9178_1_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyepsg=0.4.0=py_0
  - pyevtk=1.5.0=pyh8a188c0_0
  - pyfftw=0.13.1=py310ha9ca8c9_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pykrige=1.7.0=py310h9b08ddd_1
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py310hcdd211a_0
  - pyqt=5.15.7=py310h1fd54f2_3
  - pyqt5-sip=12.11.0=py310h00ffb61_3
  - pyrsistent=0.19.3=py310h8d17308_0
  - pyshp=2.3.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - pystackreg=0.2.7=py310h1c4a608_1
  - python=3.10.11=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-graphviz=0.16=pyhd3deb0d_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py310h5588dad_3
  - pyviz_comms=2.2.1=pyhd8ed1ab_1
  - pywavelets=1.4.1=py310h9b08ddd_0
  - pywin32=304=py310h00ffb61_2
  - pywinpty=2.0.10=py310h00ffb61_0
  - pyyaml=6.0=py310h8d17308_5
  - qt-main=5.15.8=h88fe7eb_7
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - rasterio=1.3.6=py310h32636bd_0
  - re2=2023.02.02=h63175ca_0
  - regex=2023.5.5=py310h8d17308_0
  - remotezip=0.12.1=py310h5588dad_2
  - requests=2.29.0=pyhd8ed1ab_0
  - retry=0.9.2=py_0
  - retrying=1.3.3=py_2
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.3.5=pyhd8ed1ab_0
  - rioxarray=0.14.1=pyhd8ed1ab_0
  - rtree=1.0.1=py310h1cbd46b_1
  - scikit-image=0.20.0=py310h1c4a608_1
  - scikit-learn=1.2.2=py310hd266714_1
  - scipy=1.10.1=py310h578b7cb_3
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - seaborn-image=0.6.0=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh08f2357_0
  - setuptools=67.7.2=pyhd8ed1ab_0
  - shapely=2.0.1=py310h91617ff_1
  - sip=6.7.9=py310h00ffb61_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - spectral=0.23.1=pyh1a96a4e_0
  - sqlite=3.41.2=hcfcfb64_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h9b08ddd_1
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.9.0=h91493d7_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.0=pyh08f2357_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2023.4.12=pyhd8ed1ab_0
  - tiledb=2.13.2=h3132609_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - tzlocal=4.3=py310h5588dad_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py310h8d17308_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xarray=2023.4.2=pyhd8ed1ab_0
  - xerces-c=3.2.4=h63175ca_2
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zarr=2.14.2=pyhd8ed1ab_0
  - zeromq=4.3.4=h0e60522_1
  - zfp=1.0.0=h63175ca_3
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_4
  - zlib-ng=2.0.7=hcfcfb64_0
  - zstd=1.5.2=h12be248_6
  - pip:
      - absl-py==1.4.0
      - accessible-pygments==0.0.4
      - aiohttp==3.8.4
      - aioice==0.9.0
      - aiortc==1.5.0
      - aiosignal==1.3.1
      - akhdefo-functions==2.2.58
      - alabaster==0.7.13
      - altair==5.1.1
      - ansi2html==1.8.0
      - apptools==5.2.1
      - apscheduler==3.10.1
      - arrow==1.2.3
      - astunparse==1.6.3
      - async-timeout==4.0.2
      - autodocsumm==0.2.11
      - av==10.0.0
      - babel==2.12.1
      - blinker==1.6.2
      - blosc2==2.2.9
      - brotli==1.1.0
      - build==1.0.3
      - cachelib==0.9.0
      - colorlog==6.7.0
      - commonmark==0.9.1
      - comtypes==1.2.0
      - configargparse==1.7
      - configobj==5.0.8
      - css-html-js-minify==2.5.5
      - cypari==2.5.4
      - dash==2.14.1
      - dash-bootstrap-components==1.4.1
      - dash-canvas==0.1.0
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-extensions==1.0.1
      - dash-html-components==2.0.0
      - dash-leaflet==0.1.26
      - dash-resumable-upload==0.0.3
      - dash-table==5.0.0
      - dask==2023.9.2
      - distributed==2023.9.2
      - dnspython==2.4.2
      - docopt==0.6.2
      - docutils==0.19
      - dxcam==0.0.5
      - easyprocess==1.1
      - editorconfig==0.12.3
      - entrypoint2==1.1
      - envisage==7.0.3
      - ezdxf==1.1.0
      - filelock==3.12.4
      - flask==2.3.2
      - flask-caching==2.0.2
      - flatbuffers==23.5.26
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - furo==2023.9.10
      - fxrays==1.3.5
      - gast==0.4.0
      - geobuf==1.1.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - google-crc32c==1.5.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h11==0.14.0
      - httpcore==0.17.0
      - httpx==0.24.0
      - ifaddr==0.2.0
      - imagesize==1.4.1
      - imutils==0.5.4
      - insegel==1.3.1
      - ipycanvas==0.13.1
      - ipydatawidgets==4.3.5
      - ipyevents==2.0.2
      - ipyvtklink==0.2.3
      - ipywidgets==7.8.0
      - iso8601==2.0.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jaraco-classes==3.2.3
      - jax==0.4.12
      - jsbeautifier==1.14.8
      - jsonpointer==2.4
      - jupyterlab-widgets==1.1.5
      - kaleido==0.2.1
      - keras==2.12.0
      - keyring==24.0.0
      - knot-floer-homology==1.2
      - libclang==16.0.0
      - livereload==2.6.3
      - low-index==1.2
      - lxml==5.0.0
      - m3u8==3.6.0
      - mayavi==4.8.1
      - mdit-py-plugins==0.4.0
      - ml-dtypes==0.2.0
      - more-itertools==9.1.0
      - mpld3==0.5.9
      - mplstereonet==0.6.2
      - msgpack==1.0.7
      - msgpack-numpy==0.4.8
      - mss==9.0.1
      - multidict==6.0.4
      - mutagen==1.47.0
      - myst-parser==2.0.0
      - nbformat==5.7.0
      - nbsphinx==0.9.2
      - ndindex==1.7
      - numexpr==2.8.7
      - numpy==1.23.5
      - numpy-stl==3.0.1
      - oauthlib==3.2.2
      - open3d==0.17.0
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.8.0.76
      - opt-einsum==3.3.0
      - pandas==2.1.1
      - pipreq==0.4
      - pipreqs==0.4.13
      - pkginfo==1.9.6
      - planet==2.2
      - plink==2.4.2
      - plotly==5.18.0
      - plyfile==1.0.1
      - protobuf==4.23.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycryptodomex==3.19.0
      - pydata-sphinx-theme==0.14.4
      - pydeck==0.8.0
      - pydot==1.4.2
      - pyee==11.0.0
      - pyface==8.0.0
      - pyflow==0.3.1
      - pyjwt==2.7.0
      - pylibsrtp==0.8.0
      - pympler==1.0.1
      - pynput==1.7.6
      - pyntcloud==0.3.1
      - pypng==0.20220715.0
      - pyproject-hooks==1.0.0
      - pyscreenshot==3.1
      - python-ffmpeg-video-streaming==0.1.15
      - python-slugify==8.0.1
      - python-utils==3.7.0
      - pythreejs==2.4.2
      - pyvista==0.42.1
      - pywavefront==1.3.3
      - pywin32-ctypes==0.2.1
      - pyzmq==24.0.1
      - readme-renderer==40.0
      - recommonmark==0.7.1
      - requests-oauthlib==1.3.1
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rsa==4.9
      - scooby==0.7.2
      - simplejpeg==1.7.2
      - smmap==5.0.1
      - snappy-manifolds==1.1.2
      - snowballstemmer==2.2.0
      - spherogram==2.2.1
      - sphinx==6.2.1
      - sphinx-autobuild==2021.3.14
      - sphinx-basic-ng==1.0.0b2
      - sphinx-book-theme==1.1.0
      - sphinx-gallery==0.13.0
      - sphinx-material==0.0.36
      - sphinx-orange-book-theme==0.2.0
      - sphinx-rtd-theme==2.0.0
      - sphinx-theme==1.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.9
      - starlette==0.31.1
      - streamlit==1.26.0
      - streamlit-webrtc==0.47.0
      - sympy==1.12
      - tables==3.9.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.0
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - text-unidecode==1.3
      - torch==2.0.1
      - tornado==6.4
      - traits==6.4.2
      - traitsui==8.0.0
      - traittypes==0.2.1
      - trame==3.3.0
      - trame-client==2.14.0
      - trame-server==2.13.1
      - trimesh==3.23.5
      - tripy==1.0.0
      - twine==4.0.2
      - unidecode==1.3.7
      - unpackqa==0.2.1
      - uri-template==1.3.0
      - utm==0.7.0
      - uvicorn==0.23.2
      - validators==0.22.0
      - vidgear==0.3.2
      - vtk==9.2.6
      - watchdog==3.0.0
      - webcolors==1.13
      - websockets==11.0.3
      - werkzeug==2.3.4
      - widgetsnbextension==3.6.5
      - wrapt==1.14.1
      - wslink==1.12.4
      - yarg==0.1.9
      - yarl==1.9.2
      - yt-dlp==2023.9.24

